name: linter-check
on: [push]
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: install poetry
        run: pip install poetry
      - name: run-linter
        run:  make lint
